# Generated by Django 4.1.2 on 2023-02-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact-Us',
            },
        ),
    ]
